---
- name: Remove old SSH host keys
  ansible.builtin.file:
    path: "/etc/ssh/{{ item }}"
    state: absent
  loop:
    - ssh_host_rsa_key
    - ssh_host_rsa_key.pub
    - ssh_host_ed25519_key
    - ssh_host_ed25519_key.pub

- name: Generate new RSA and ED25519 host keys
  ansible.builtin.shell:
    cmd: "ssh-keygen -t {{ item.type }} -b {{ item.bits }} -f /etc/ssh/ssh_host_{{ item.type }}_key -N ''"
    creates: "/etc/ssh/ssh_host_{{ item.type }}_key"
  loop:
    - { type: 'rsa', bits: 4096 }
    - { type: 'ed25519', bits: '' }
