---
- name: Remove small Diffie-Hellman moduli
  ansible.builtin.shell:
    cmd: "awk '$5 >= 3071' /etc/ssh/moduli > /etc/ssh/moduli.safe && mv /etc/ssh/moduli.safe /etc/ssh/moduli"
    args:
      creates: "/etc/ssh/moduli.safe"
